---

# Naive Bayes Classification(나이브 베이즈 분류)
2017.11.27<br>
박지훈

---

__베이즈 정리(Bayes's Theorem)__: 불확실성 하에서 의사결정문제를 수학적으로 다둘 때 중요하게 사용된다. 전통적인 확률이 연역적 추론에 기반을 두고 있다면 베이즈 정리는 확률임에도 불구하고 귀납적, 경험적인 추론을 사용한다. <br>
$$P(A|B) = \frac{P(B|A)P(A)}{P(B)}$$ <br>

__조건부 확률(Conditional Probability)__: 어떤 특정 사건 B가 발생했을때 사건 A가 발생할 확률 수식으로는 $P(A|B)$ 로 표현한다.<br>
각 사건이 독립일 경우 조건부 확률은 각 사건의 곱과 같다. 그러므로 $P(A|B) = P(A)$이고 $P(B|A) = P(B)$ 이다. <br>

__라플라스 스무딩(Laplace Smoothing)__: 그 전에 관측되지 못한 새로운 데이터를 분류해야 할때 확률값이 0이되는걸 막기위해 분자와 분모에 1씩 더한다.

---

In [1]:
# importing packages
import numpy as np

In [45]:
# make a dataset
def make_data():
    data = np.array([[1, 0, 1, 0],
                     [1, 1, 1, 1], 
                     [1, 0, 0, 1], 
                     [0, 0, 1, 1], 
                     [1, 1, 1, 0], 
                     [0, 0, 1, 0], 
                     [0, 1, 0, 1], 
                     [1, 0, 1, 0], 
                     [1, 0, 0, 0], 
                     [0, 0, 1, 1]])
    
    classes = np.array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0])
    
    return data, classes

In [139]:
def count_prob(dataset, classes):
    
    label = np.unique(classes)
    class_prob = []
    data_split = []
    con_prob = []
    con_prob_2 = []
    temp = []
    prob = []
    
    for i in label:
        class_prob.append(len(classes[classes==i])/len(classes))
        data_split.append(dataset[classes==i])
    
    for j in range(len(data_split)):
#        con_prob.append(np.sum(data_split[j], axis=0))
        
        for k in label:
            
            for l in range(len(dataset[0])):
                temp.append(len(data_split[j][data_split[j][:, l]==k])/len(data_split[j]))

            con_prob_2.append(temp)
            temp = []
    
#    for n in range(len(data_split)):
#        prob.append(con_prob[n]/len(data_split[n]))

    return label, class_prob, data_split, con_prob_2

In [89]:
def classification(dataset, classes, classification_data):
    label, class_prob, data_split, con_prob_2 = count_prob(data, classes)
    class_prob_2

In [22]:
data, classes = make_data()

In [140]:
label, class_prob, data_split, con_prob_2 = count_prob(data, classes)

In [135]:
count_prob(data, classes)

(array([0, 1]), [0.6, 0.4], [array([[1, 1, 1, 0],
         [0, 0, 1, 0],
         [0, 1, 0, 1],
         [1, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 1]]), array([[1, 0, 1, 0],
         [1, 1, 1, 1],
         [1, 0, 0, 1],
         [0, 0, 1, 1]])], [[[0.5,
    0.6666666666666666,
    0.3333333333333333,
    0.6666666666666666]],
  [[0.5, 0.3333333333333333, 0.6666666666666666, 0.3333333333333333]],
  [[0.25, 0.75, 0.25, 0.25]],
  [[0.75, 0.25, 0.75, 0.75]]])

In [144]:
con_prob_2

[[0.5, 0.6666666666666666, 0.3333333333333333, 0.6666666666666666],
 [0.5, 0.3333333333333333, 0.6666666666666666, 0.3333333333333333],
 [0.25, 0.75, 0.25, 0.25],
 [0.75, 0.25, 0.75, 0.75]]

In [147]:
np.log2(con_prob_2)

array([[-1.       , -0.5849625, -1.5849625, -0.5849625],
       [-1.       , -1.5849625, -0.5849625, -1.5849625],
       [-2.       , -0.4150375, -2.       , -2.       ],
       [-0.4150375, -2.       , -0.4150375, -0.4150375]])

In [27]:
prob

[array([ 0.5       ,  0.33333333,  0.66666667,  0.33333333]),
 array([ 0.75,  0.25,  0.75,  0.75])]

In [17]:
e

[array([ 0.5       ,  0.33333333,  0.66666667,  0.33333333]),
 array([ 0.75,  0.25,  0.75,  0.75])]